name: loop_page_view
description: A simple Flutter PageView builder constructor wrapper that allows for endless scrolling on both directions.
version: 1.2.5
homepage: https://github.com/wjuniorgit/loop_page_view
repository: https://github.com/wjuniorgit/loop_page_view

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter